// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2051.RecycleRush.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2051.RecycleRush.Robot;

/**
 * This command enables or disables the gyroscope
 * It's intended to be on a toggle button (in IO.java)
 * The first press will run this command, putting the gyro into disabled state
 * The second press will kill this command, re-enabling the gyro
 * In between time, the command runs continuously
 */
public class DisableGyro extends Command
{

	public DisableGyro()
	{
		// Use requires() here to declare subsystem dependencies
		requires(Robot.driveGyro);

		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	}

	// Called just before this Command runs the first time
	protected void initialize()
	{
		Robot.driveGyro.gyroDisable();
	}

	// Called repeatedly when this Command is scheduled to run
	protected void execute()
	{
	}

	// Make this return true when this Command no longer needs to run execute()
	// This command never finishes. The toggle button action will kill it when needed.
	protected boolean isFinished()
	{
		return false;
	}
	

	// Called once after isFinished returns true
	protected void end()
	{
		Robot.driveGyro.gyroEnable();
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	protected void interrupted()
	{
		end();
	}
}
