// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2051.RecycleRush.commands;

import org.usfirst.frc2051.RecycleRush.Robot;

import edu.wpi.first.wpilibj.command.Command;

/**
 * This command is one of the options for autonomous.
 * It's supposed to do absolutely nothing, holding the robot in it's place.
 */
public class DoNothing extends Command
{

	public DoNothing()
	{
		// Use requires() here to declare subsystem dependencies
		//requires(Robot.subsystem);
	}

	// Called just before this Command runs the first time
	protected void initialize()
	{
	}

	// Called repeatedly when this Command is scheduled to run
	protected void execute()
	{
		//do nothing
	}

	// Make this return true when this Command no longer needs to run execute()
	// This command never finishes. The toggle button action will kill it when needed.
	protected boolean isFinished()
	{
		return false;
	}
	

	// Called once after isFinished returns true
	protected void end()
	{
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	protected void interrupted()
	{
		end();
	}
}
